### ISSUE TITLE
Cash parsing exception

### ISSUE THREAD

**Issue by yegor256** [zerocracy/jstk#30]
Let's make it checked.

**Comment by yegor256** [comment]
@rultor release, tag is `0.17`

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT c8416b2 2017-10-17T10:16:10
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/finish_order.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/finish_order.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:87)
	at com.zerocracy.farm.reactive.brigade.StkWithStatus.process(StkWithStatus.java:55)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:101)
	at com.zerocracy.farm.reactive.Brigade.lambda$process$0(Brigade.java:83)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.value(LengthOf.java:56)
	at org.cactoos.iterable.LengthOf.value(LengthOf.java:56)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:85)
	at com.zerocracy.farm.reactive.Flush.process(Flush.java:86)
	at com.zerocracy.farm.reactive.Flush.exec(Flush.java:71)
	at com.zerocracy.farm.reac...
```

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/jstk#30` was not in scope
