### ISSUE TITLE
Project.Proxy and Farm.Proxy

### ISSUE THREAD

**Issue by yegor256** [zerocracy/jstk#32]
Let's add them.

**Comment by yegor256** [comment]
@rultor release, tag is `0.19`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.1`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
	at com...
```

My version: `1.0-SNAPSHOT`, `4fbcb81`, `2017-10-30T15:19:50` /cc @yegor256

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/jstk#32`.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/jstk#32`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/jstk#32` is not in scope.
